import {courses} from '../assets'
export const onlineCourses = [
    {
        id: 'oncrs-1',
        title: `Project Management`,
        category: 'Upgrade skill',
        description: `In this course, we'll learn to code, starting from the basic blocks. No kidding! Scratch, the programming`,
        lession: 2,
        time: '05:00',
        price: 0,
        discountPrice: 0,
        sales: 7,
        rating: "5",
        owner: "Sheldon Cottrell",
        thumbnail: courses.course1,
        keyword: ['Project', 'Management'],
        date: 1692761450728
    },
    {
        id: 'oncrs-2',
        title: `Programming for Kids`,
        category: 'Personal Development',
        description: `In this course, we'll learn to code, starting from the basic blocks. No kidding! Scratch, the programming`,
        lession: 2,
        time: '05:00',
        price: 150.50,
        discountPrice: 120.00,
        sales: 10,
        rating: "5",
        owner: "Sheldon Cottrell",
        thumbnail: courses.course2,
        keyword: ['Programming', 'Kid'],
        date: 1692761450828
    },
    {
        id: 'oncrs-3',
        title: `Learn React the Easy Way`,
        category: 'Personal Development',
        description: `In this course, we'll learn to code, starting from the basic blocks. No kidding! Scratch, the programming`,
        lession: 2,
        time: '05:00',
        price: 200.50,
        discountPrice: 180.00,
        sales: 2,
        rating: "5",
        owner: "Sheldon Cottrell",
        thumbnail: courses.course3,
        keyword: ['react'],
        date: 1692761450928
    },
    {
        id: 'oncrs-4',
        title: `Life with Nature`,
        category: 'Lifestyle Course',
        description: `In this course, we'll learn to code, starting from the basic blocks. No kidding! Scratch, the programming`,
        lession: 2,
        time: '05:00',
        price: 280.50,
        discountPrice: 260.00,
        sales: 11,
        rating: "5",
        owner: "Sheldon Cottrell",
        thumbnail: courses.course4,
        keyword: ['life', 'nature'],
        date: 1692761451728
    },
    {
        id: 'oncrs-5',
        title: `Learn with Play`,
        category: 'Health & Fitness',
        description: `In this course, we'll learn to code, starting from the basic blocks. No kidding! Scratch, the programming`,
        lession: 2,
        time: '05:00',
        price: 350.50,
        discountPrice: 310.00,
        sales: 4,
        rating: "5",
        owner: "Sheldon Cottrell",
        thumbnail: courses.course5,
        keyword: ["health", 'play', 'fitness'],
        date: 1692761452728
    },
    {
        id: 'oncrs-6',
        title: `Programming for Kids`,
        category: 'Upgrade skill',
        description: `In this course, we'll learn to code, starting from the basic blocks. No kidding! Scratch, the programming`,
        lession: 2,
        time: '05:00',
        price: 300.50,
        discountPrice: 330.00,
        sales: 5,
        rating: "5",
        owner: "Sheldon Cottrell",
        thumbnail: courses.course6,
        keyword: ['Programming', 'Kid'],
        date: 1692761453728
    },
    {
        id: 'oncrs-7',
        title: `Programming for Kids`,
        category: 'Upgrade skill',
        description: `In this course, we'll learn to code, starting from the basic blocks. No kidding! Scratch, the programming`,
        lession: 2,
        time: '05:00',
        price: 450.50,
        discountPrice: 420.00,
        sales: 8,
        rating: "3",
        owner: "Sheldon Cottrell",
        thumbnail: courses.course7,
        keyword: ['Programming', 'Kid'],
        date: 1692761454728
    },
    {
        id: 'oncrs-8',
        title: `Marketing effectively in English`,
        category: 'Business Marketing',
        description: `In this course, we'll learn to code, starting from the basic blocks. No kidding! Scratch, the programming`,
        lession: 2,
        time: '05:00',
        price: 550.50,
        discountPrice: 510.00,
        sales: 6,
        rating: "4",
        owner: "Sheldon Cottrell",
        thumbnail: courses.course8,
        keyword: ['english1', 'marketing'],
        date: 1692761455728
    },
    
]